#!/bin/bash

#while :
#do

echo -e "\e[96m==============================================================\e[0m"
echo -e "\e[96m                 Welcome to Mail Server\e[0m"
echo -e "\e[96m==============================================================\e[0m"

echo "1. Verification of Account"
echo "2. Account Creation"
#echo "3. Account Deletion"
read -p "Please Enter your choice :" x

        case $x in
                1)
                        #echo "Please Enter the User Name :"
                        'verify'
#                       echo -e "\e[93m#######################################################################\e[0m"
                        './auto'
                        ;;
                2)
                        #echo "Please provide the user name here :"
                        'acc'
#                       echo -e "\e[93m#######################################################################\e[0m"
                        './auto'
                        ;;
#               3)
#                       'finaldel'
#                       echo -e "\e[93m#######################################################################\e[0m"
#                       './test'
#                       ;;
                  *)
                        exit
        esac
#done

